services:
  web:
    build: .
    container_name: flask-pipeline-demo
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_RUN_PORT=5000
    volumes:
      - ./data:/app/data
    restart: unless-stopped
